name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Fix permissions of fonts
        run: sudo chmod -R 755 /usr/share/fonts

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting with Prettier
        run: npx prettier --check .

      - name: Run tests
        run: npm run test
